version: '3'

services:
  cluster-master:
    build: ./docker
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
    container_name: cluster-master
    hostname: cluster-master
    volumes:
      - ./config/cluster-master-etc/:${SPLUNK_ETC_SYSTEM}
      - ./config/cluster-master-var/var/log:${SPLUNK_VAR_LOG}:z
      - ./cluster-master:/opt/splunk/etc/apps/cluster-master:z 


    ports:
      - 9000:8000
    labels:
      splunk.cluster: "cluster-master"
    networks:
      splunk:
        aliases:
          - cluster-master

  deployment-server:
    image: splunk/splunk:7.2
    # deploy:
    #   resourcess:
    #     limits:
    #       cpus: 1
    #       memory: 1G
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
    container_name: deployment-server
    hostname: deployment-server
    volumes:
      - ./config/deployment-server-etc/:${SPLUNK_ETC_SYSTEM}:z
      - ./config/deployment-server-etc/deployment-apps:${SPLUNK_ETC_SYSTEM}:z
      - ./config/deployment-server-var/:${SPLUNK_VAR_LOG}:z
    ports:
      - 10000:8000
    labels:
      splunk.cluster: "deployment-server"
    networks:
      splunk:
        aliases:
          - deployment-server

  shc-member-01:
    image: splunk/splunk:7.2
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
    container_name: shc-member-01
    hostname: shc-member-01

    ports:
      - 11000:8000
    labels:
      splunk.cluster: "shc-member"
    networks:
      splunk:
        aliases:
          - shc-member-01

  idx-member-01:
    image: splunk/splunk:7.2      
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
    container_name: idx-member-01
    hostname: idx-member-01
    volumes:
      - ./config/idx-member-etc:${SPLUNK_ETC_SYSTEM}:z
      - ./config/idx-member-01-var:${SPLUNK_VAR_LOG}:z
      - ./config/splunkindexes/idx-member-01:/apps/splunkindexes:z
      - ./idx-member:/opt/splunk/etc/apps/idx-member:z
    ports:
      - 8003:8000
    labels:
      splunk.cluster: "idx-member-01"
    networks:
      splunk:
        aliases:
          - idx-member-01

  idx-member-02:
    image: splunk/splunk:7.2
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
    container_name: idx-member-02
    volumes:
      - ./config/idx-member-01-etc/:${SPLUNK_ETC_SYSTEM}:z
      - ./config/idx-member-02-var/:${SPLUNK_VAR_LOG}:z
      - ./config/splunkindexes/idx-member-02:/apps/splunkindexes:z
      - ./idx-member:/opt/splunk/etc/apps/idx-member:z
    hostname: idx-member-02
    ports:
      - 8004:8000
    labels:
      splunk.cluster: "idx-member-02"
    networks:
      splunk:
        aliases:
          - idx-member-02

  idx-member-03:
    image: splunk/splunk:7.2
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
    container_name: idx-member-03
    volumes:
      - ./config/idx-member-03-etc:${SPLUNK_ETC_SYSTEM}:z
      - ./config/idx-member-03-var:${SPLUNK_VAR_LOG}:z
      - ./config/splunkindexes/idx-member-03:/apps/splunkindexes:z
      - ./idx-member:/opt/splunk/etc/apps/idx-member
    hostname: idx-member-03
    ports:
      - 8005:8000
    labels:
      splunk.cluster: "idx-member-03"
    networks:
      splunk:
        aliases:
          - idx-member-03


volumes:
   config:
   cluster-master-etc:
   idx-member:
networks:
  splunk:
